### ISSUE TITLE
Script throws "TypeError: Object of type bytes is not JSON serializable"

### ISSUE THREAD

**Issue by tuxick** [narbehaj/zabbix-nvme#2]
`./nvme_discover.py nvme_list`

was giving me:

```
Traceback (most recent call last):
  File "./nvme_discover.py", line 26, in <module>
    get_nvme_list()
  File "./nvme_discover.py", line 16, in get_nvme_list
    print(json.dumps(data_list))
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

```

I'm not very good at python, but this fixes it for me:

```
    stdraw = subprocess.check_output("sudo nvme list | grep '/dev/' | awk '{print $1}'", shell=True)
    stdout = stdraw.decode()

```
```

**Comment by narbehaj** [comment]
Thanks for the feedback, this was related to the python 2 and 3 versions. All ok now.
